language: python
python:
  - "3.4"
install:
  - pip install flake8
  - pip install boto
  - pip install stups-pierone
script:
  - flake8 -v .
  - python3 -m doctest -v runtime/usr/local/lib/python3.4/dist-packages/taupage/__init__.py
  - PYTHONPATH=runtime/usr/local/lib/python3.4/dist-packages python3 -m doctest -v runtime/opt/taupage/runtime/Docker.py
  - PYTHONPATH=runtime/usr/local/lib/python3.4/dist-packages python3 -m doctest -v runtime/opt/taupage/init.d/00-push-taupage-yaml.py
  - PYTHONPATH=runtime/usr/local/lib/python3.4/dist-packages python3 -m doctest -v runtime/opt/taupage/bin/push-audit-logs.py
